### ISSUE TITLE
Manjaro无法运行，shell没有任何输出。

### ISSUE THREAD

**Issue by lronkitty** [rikonaka/rust-translator#1]
大佬你好，很感兴趣您的项目，目前遇到问题Manjaro无法运行，shell没有任何输出。有没有啥debug模式？有空我自己编译试试。

**Comment by rikonaka** [comment]
@lronkitty 你好，抱歉这么晚才回复，debug模式还未开发，不过既然说了，那我就写一个，实在不好意思啊，我现在装个 Manjaro 的虚拟机测试一下 😘😘😘，顺便问一句你的桌面环境是哪个？ Gnome 还是 Plasma

**Comment by rikonaka** [comment]
@lronkitty 你好，我在 kubuntu上 测试了一下，如果你的桌面环境是 KDE 的 Plama 的话应该是没有问题的，现在只剩 xfce 没有测试
![image](https://user-images.githubusercontent.com/13602602/192968329-e95fd4b0-011c-48d6-9f1e-5484ef16708a.png)

**Comment by rikonaka** [comment]
@lronkitty 我想起来了，最近谷歌的API被封了，所以之前的代码没有设置 HTTP GET 的 TIMEOUT 所以会一直没有任何输出，现在的代码你设置一个代理就可以了，我现在加了一个9秒的 TIMEOUT 所以如果是网络问题的话，很快就可以报错了，如果你想 DEBUG 程序的话，直接在代码里面加 println! （print调试大法😂😂😂）

**Comment by lronkitty** [comment]
感谢作者，我用musl版本的可以用，另一个版本会报segmentation fault (core dumped)

**Comment by rikonaka** [comment]
> 感谢作者，我用musl版本的可以用，另一个版本会报segmentation fault (core dumped)

那就好😍
