### ISSUE TITLE
error sending request for url ,, operation time out

### ISSUE THREAD

**Issue by CXT-666** [rikonaka/rust-translator#2]
translate failed: error sending request for url (https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=zh-CN&dt=t&q=ranslate%20failed:%20error%20sending%20request%20for%20url%20(https://translate.googleapis.com/translate_a/single?client=gtx%26sl=en%26tl=zh-CN%26dt=t%26q=Gnome%2520Document%2520Viewer):%20operation%20timed%20out): operation timed out
translate failed: error sending request for url (https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=zh-CN&dt=t&q=failed:%20error%20sending%20request%20for%20url): operation timed out
translate failed: error sending request for url (https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=zh-CN&dt=t&q=translate%20failed:%20error%20sending%20request%20for%20url%20(https://translate.googleapis.com/translate_a/single?client=gtx%26sl=en%26tl=zh-CN%26dt=t%26q=ranslate%2520failed:%2520error%2520sending%2520request%2520for%2520url%2520(https://translate.googleapis.com/translate_a/single?client=gtx%2526sl=en%2526tl=zh-CN%2526dt=t%2526q=Gnome%252520Document%252520Viewer):%2520operation%2520timed%2520out):%20operation%20timed%20out): operation timed out
你好大佬，请问为挂了taiwan代理一直显示超时，有什么解决办法吗

**Comment by rikonaka** [comment]
> translate failed: error sending request for url (https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=zh-CN&dt=t&q=ranslate%20failed:%20error%20sending%20request%20for%20url%20(https://translate.googleapis.com/translate_a/single?client=gtx%26sl=en%26tl=zh-CN%26dt=t%26q=Gnome%2520Document%2520Viewer):%20operation%20timed%20out): operation timed out
> translate failed: error sending request for url (https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=zh-CN&dt=t&q=failed:%20error%20sending%20request%20for%20url): operation timed out
> translate failed: error sending request for url (https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=zh-CN&dt=t&q=translate%20failed:%20error%20sending%20request%20for%20url%20(https://translate.googleapis.com/translate_a/single?client=gtx%26sl=en%26tl=zh-CN%26dt=t%26q=ranslate%2520failed:%2520error%2520sending%2520request%2520for%2520url%2520(https://translate.googleapis.com/translate_a/single?client=gtx%2526sl=en%2526tl=zh-CN%2526dt=t%2526q=Gnome%252520Document%252520Viewer):%2520operation%2520timed%2520out):%20operation%20timed%20out): operation timed out
> 你好大佬，请问为挂了taiwan代理一直显示超时，有什么解决办法吗

因为Google翻译被墙了，看样子你的代理好像有点问题，要么延迟比较高😂，可以先测试测试代理延迟

**Comment by rikonaka** [comment]
> translate failed: error sending request for url (https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=zh-CN&dt=t&q=ranslate%20failed:%20error%20sending%20request%20for%20url%20(https://translate.googleapis.com/translate_a/single?client=gtx%26sl=en%26tl=zh-CN%26dt=t%26q=Gnome%2520Document%2520Viewer):%20operation%20timed%20out): operation timed out translate failed: error sending request for url (https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=zh-CN&dt=t&q=failed:%20error%20sending%20request%20for%20url): operation timed out translate failed: error sending request for url (https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=zh-CN&dt=t&q=translate%20failed:%20error%20sending%20request%20for%20url%20(https://translate.googleapis.com/translate_a/single?client=gtx%26sl=en%26tl=zh-CN%26dt=t%26q=ranslate%2520failed:%2520error%2520sending%2520request%2520for%2520url%2520(https://translate.googleapis.com/translate_a/single?client=gtx%2526sl=en%2526tl=zh-CN%2526dt=t%2526q=Gnome%252520Document%252520Viewer):%2520operation%2520timed%2520out):%20operation%20timed%20out): operation timed out 你好大佬，请问为挂了taiwan代理一直显示超时，有什么解决办法吗

这个问题今天我也遇见了，修改 Linux 系统的 DNS 到 114.114.114.114 还有 8.8.8.8 就好了😂
