### ISSUE TITLE
使用 Zotero 无法读取屏幕取词

### ISSUE THREAD

**Issue by brilliantrough** [rikonaka/rust-translator#3]
作者你好！看了你的这个工程，我发现它基本可以在所有能取词的地方都能识别并翻译。无论是 PDF，还是网页，终端，这让我非常喜欢。但是我（Ubuntu 20.04 系统）在用 zotero 阅读英文文献时发现其无法从zotero内置的PDF阅读器中读取屏幕取词。不知作者大大是否能够小小改进一下。感激不尽！

**Comment by KarmaRich** [comment]
遇到同样的问题，使用系统自带的pdf阅读器选中可以翻译，在zotero中选中却不行，复制可以。 @rikonaka

**Comment by rikonaka** [comment]
> 作者你好！看了你的这个工程，我发现它基本可以在所有能取词的地方都能识别并翻译。无论是 PDF，还是网页，终端，这让我非常喜欢。但是我（Ubuntu 20.04 系统）在用 zotero 阅读英文文献时发现其无法从zotero内置的PDF阅读器中读取屏幕取词。不知作者大大是否能够小小改进一下。感激不尽！

我还没用过zotero，过几天我看看，最近忙着写论文所以回复慢了，不好意思🥰

**Comment by rikonaka** [comment]
> 遇到同样的问题，使用系统自带的pdf阅读器选中可以翻译，在zotero中选中却不行，复制可以。 @rikonaka 

好的，感谢反馈，我这几天就看看那个工具🥳

**Comment by rikonaka** [comment]
> 作者你好！看了你的这个工程，我发现它基本可以在所有能取词的地方都能识别并翻译。无论是 PDF，还是网页，终端，这让我非常喜欢。但是我（Ubuntu 20.04 系统）在用 zotero 阅读英文文献时发现其无法从zotero内置的PDF阅读器中读取屏幕取词。不知作者大大是否能够小小改进一下。感激不尽！

现在有个解决方法就是选中要翻译文字的时候使用复制 `ctrl-c` 来将文字传递给程序，这个功能已经在最新版里面实现了😘。

**Comment by rikonaka** [comment]
> 遇到同样的问题，使用系统自带的pdf阅读器选中可以翻译，在zotero中选中却不行，复制可以。 @rikonaka

现在有个解决方法就是选中要翻译文字的时候使用复制 ctrl-c 将文字传递给程序，这个功能已经在最新版里面实现了😘。
因为 zotero 的选中被 zotero 程序自身拦截了到不了系统层面，现在只能使用复制才能将文字传递给程序。

**Comment by fecet** [comment]
zathura貌似也不行, zathura选中会默认传到剪贴板, 不知道什么原因没法翻译

**Comment by rikonaka** [comment]
> zathura貌似也不行, zathura选中会默认传到剪贴板, 不知道什么原因没法翻译

因为无法从某些软件中获得选中的文本，所以在这些应用中选中文本之后，按 ctrl-c 复制到系统剪切板，程序再从剪切板中读取数据翻译😂，这样也不行吗？

**Comment by fecet** [comment]
![image](https://user-images.githubusercontent.com/41792945/212310933-210c64cd-0d8f-476e-948f-e30d894e8dc5.png)

zathura显示已经放到剪贴板了, 粘贴也确实有效, 但翻译器没有接受到

**Comment by rikonaka** [comment]
> ![image](https://user-images.githubusercontent.com/41792945/212310933-210c64cd-0d8f-476e-948f-e30d894e8dc5.png)
> 
> zathura显示已经放到剪贴板了, 粘贴也确实有效, 但翻译器没有接受到

不好意思这才看见，这就有点奇怪了，我现在打开Ubuntu测试一下看看

**Comment by rikonaka** [comment]
![Ubuntu22 04-2023-01-27-21-41-13](https://user-images.githubusercontent.com/13602602/215100891-3c648b07-b54f-4fa4-82d6-21b1879254a6.png)

经过测试，是可以从系统粘贴板中获得内容的，测试没有问题😘

**Comment by fecet** [comment]
zotero是可以通过复制解决的，zathura是另一个软件，pdf阅读器

**Comment by rikonaka** [comment]
@fecet 不好意思看错了😜，刚刚测试了一下，zathura 还是可以的，zathura 直接选就行了。只不过这个软件有点简单，选的时候识别不太准确。

[Screencast](https://user-images.githubusercontent.com/13602602/218256787-ea9e2c12-e62d-4044-9ecf-4722830e3364.webm)

![Screenshot from 2023-02-11 20-03-55](https://user-images.githubusercontent.com/13602602/218256954-91c4ac20-cc7b-430c-90e3-0d0783840c48.png)

**Comment by fecet** [comment]
> @fecet 不好意思看错了stuck_out_tongue_winking_eye，刚刚测试了一下，zathura 还是可以的，zathura 直接选就行了。只不过这个软件有点简单，选的时候识别不太准确。
> 
> ![Screenshot from 2023-02-11 20-03-55](https://user-images.githubusercontent.com/13602602/218256954-91c4ac20-cc7b-430c-90e3-0d0783840c48.png)

那可能是平台的问题..好吧
