### ISSUE TITLE
更好的TUI

### ISSUE THREAD

**Issue by fecet** [rikonaka/rust-translator#4]
现在的版本翻译会自动断句, 而且是上下排列, 经常要费点劲找到翻译段落的起点, 能否增加一些调整tui的选项

- 切换上下/左右排布
- 是否自动断句
- 是否显示原文

**Comment by rikonaka** [comment]
> 现在的版本翻译会自动断句, 而且是上下排列, 经常要费点劲找到翻译段落的起点, 能否增加一些调整tui的选项
> 
> - 切换上下/左右排布
> - 是否自动断句
> - 是否显示原文

非常好的建议，我这就开始新增功能，谢谢反馈😘

**Comment by rikonaka** [comment]
关于 tui 的问题，试了两个框架学习成本太高写不动了，其他功能完成了两个🤣

- [ ] 切换上下/左右排布
- [x] 是否自动断句
- [x] 是否显示原文

**Comment by fecet** [comment]
这两个也很有帮助了, 感谢作者的辛苦付出
