### ISSUE TITLE
翻译一次后会显示之前的翻译

### ISSUE THREAD

**Issue by Cold-Stars** [rikonaka/rust-translator#5]
![image](https://user-images.githubusercontent.com/113192545/225483075-b215498d-5f6f-4bcd-ae7c-f46318a389e4.png)
![image](https://user-images.githubusercontent.com/113192545/225483228-34e6bdf1-b263-48d6-9396-4f40e4a7dbfe.png)
![image](https://user-images.githubusercontent.com/113192545/225483367-cdf60731-0442-463a-9ce0-d78e038f470c.png)

作者你好，我每次选中翻译后好像都会显示一次上次复制的内容

**Comment by KarmaRich** [comment]
我目前的解决办法是复制一个空格然后选中翻译

**Comment by rikonaka** [comment]
你好 @Cold-Stars ，最新版本的[软件](https://github.com/rikonaka/translator-rs/releases/tag/v0.3.2)已经修复这个bug，这个问题一是由于代码中默认 Linux 上是开启从剪切板中获得文本这个选项，现在已经关闭这个选项，二是检查上个获得的文本时候没区分是从选中还是剪切板获得，所以当选中一个文本的同时按下复制，就会造成获得两个相同的文本。

PS：如果你想在 Linux 中开启同时从选中和剪切板获得文本，命令行中加入选项 `--linux-use-clipboard`

对此造成的困扰深表歉意。
