### ISSUE TITLE
大佬有没有可能支持别的api呀

### ISSUE THREAD

**Issue by lronkitty** [rikonaka/rust-translator#7]
大佬你这个是真好用，但是有没有可能提供别的api支持呀，比如deepl或者有道之类的。期待.jpg

**Comment by rikonaka** [comment]
> 大佬你这个是真好用，但是有没有可能提供别的api支持呀，比如deepl或者有道之类的。期待.jpg

我今天研究研究，主要是 <deepl> 或者 <有道> 我不确定这 API 免费不免费，实现应该不难 🤪

**Comment by lronkitty** [comment]
大佬辛苦了！

**Comment by rikonaka** [comment]
> 大佬辛苦了！

看了一下， DeepL 的 API 有免费版本的套餐，然后已经加入了支持，而 有道 的一言难尽，这玩意家里有矿啊。

![图片](https://github.com/rikonaka/translator-rs/assets/13602602/b1aa165e-481a-46a7-b057-712f78a38986)
