### ISSUE TITLE
translate failed

### ISSUE THREAD

**Issue by JensYan** [rikonaka/rust-translator#8]
'translate failed: error decoding response body: expected value at line1 column1'
How to solve this problem? And this is a good translator tool. I open it once time and I don't know why.

**Comment by rikonaka** [comment]
> 'translate failed: error decoding response body: expected value at line1 column1' How to solve this problem? And this is a good translator tool. I open it once time and I don't know why.

Hi, which translation API are you using? Google or DeepL? If you get an error, try restarting the programme 🤪.

**Comment by JensYan** [comment]
I think is Google. Because when I open it, 'working with Google' is showed. Emmm... I open it correctly right now as once as get a reply:)

**Comment by rikonaka** [comment]
> I think is Google. Because when I open it, 'working with Google' is showed. Emmm... I open it correctly right now as once as get a reply:)

Ok, that's good 😝.
